FROM ubuntu:latest
MAINTAINER Petro Shevchenko <shevchenko.p.i@gmail.com>
RUN apt-get update -y
RUN	apt-get install git cmake build-essential -y
RUN mkdir /opt/libcoapcpp
COPY scripts/docker/build.sh /opt/libcoapcpp
COPY CMakeLists.txt /opt/libcoapcpp
COPY src /opt/libcoapcpp/src
COPY api /opt/libcoapcpp/api
COPY examples /opt/libcoapcpp/examples
RUN chmod a+x /opt/libcoapcpp/build.sh
RUN cd /opt/libcoapcpp && ./build.sh
